tasks:
  - init: |
      python -m pip install --upgrade pip
    command: |
      wget https://github.com/h2oai/wave/releases/download/v0.19.0/wave-0.19.0-linux-amd64.tar.gz
      tar -xvf wave-0.19.0-linux-amd64.tar.gz
      mv wave-0.19.0-linux-amd64 ~/wave
      rm wave-0.19.0-linux-amd64.tar.gz
      cwd=$(pwd)
      cd ~/wave
      ./waved &
      cd $cwd
      [ -d "$e" ] || { echo "sample not found"; exit 1; }
      cd $e
      make setup
      make run

ports:
  - port: 10101
    visibility: public
    onOpen: open-preview

vscode:
  extensions:
    - ms-python.python
